# This is a basic workflow to help you get started with Actions

name: package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: install composer
      run:  |
        echo work space ${GITHUB_WORKSPACE}
        cd /Users/runner/runners/2.169.1/work/iRime-Resource/iRime-Resource/script/package
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer
        ls -a /Users/runner/runners/2.169.1/work/iRime-Resource/iRime-Resource/script/package

    # install yaml
    - name: update composer
      run: |
        cd /Users/runner/runners/2.169.1/work/iRime-Resource/iRime-Resource/script/package
        composer update

    - name: run package script
      env:
        ACCESSKEYID:  ${{secrets.ACCESSKEYID}}
        ACCESSKEYSECRET:  ${{secrets.ACCESSKEYSECRET}}
        ENDPOINT:  ${{secrets.ENDPOINT}}
        BUCKET:  ${{secrets.BUCKET}}
        UPLOADSCHEMAURL:  ${{secrets.UPLOADSCHEMAURL}}
      run: php /Users/runner/runners/2.169.1/work/iRime-Resource/iRime-Resource/script/package/package.php
